# -*- coding: utf-8 -*-
"""Segmentation and patching.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bLH1-UFtsj0cnVO-4BI9rKepRaQyVDk5

# PrePATH
https://github.com/birkhoffkiki/PrePATH

### Cấu trúc dataset trong Google Drive:
```
tcga-dataset/
  ├── lusc/
  │     ├── <patient_id>/
  │     │       └── slide.svs
  │     └── ...
  └── luad/
        ├── <patient_id>/
        │       └── slide.svs
        └── ...
```

### Output sau khi chạy:
```
tcga-dataset/
  ├── lusc_output
  │     ├── masks/       ← ảnh mask phân đoạn mô
  │     ├── patches/     ← tọa độ patch (.h5)
  │     ├── stitches/    ← ảnh ghép patch
  │     
  └── luad_output
        ├── masks/
        ├── patches/
        ├── stitches/

## Bước 1: Mount Google Drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""#0. Clone PrePATH"""

!git clone https://github.com/birkhoffkiki/PrePATH

"""#0.1 Cài đặt thư viện"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/PrePATH

!pip install torch==2.3.0 \
torchvision==0.18.0 \
timm==1.0.15 \
wandb \
openslide-python \
openslide-bin h5py==3.8.0 \
numpy==1.26.4 \
opencv_python==4.7.0.72 \
opencv_python_headless==4.10.0.84 \
paramiko==3.5.1 \
pathos==0.3.3 \
Pillow==11.2.1 \
PyYAML==6.0.2 \
scipy==1.15.3 \
scp==0.15.0 \
setuptools==65.6.3 \
pandas einops_exts

# Commented out IPython magic to ensure Python compatibility.
# Nâng cấp các công cụ biên dịch cốt lõi để sửa lỗi sinh metadata
!pip install --upgrade pip setuptools wheel Cython

# %cd /content/

# Clone thư viện ASlide
!git clone https://github.com/MrPeterJin/ASlide.git

# Di chuyển vào thư mục ASlide và tiến hành cài đặt
# %cd /content/ASlide
!pip install .

# Nếu không có thư viện ASlide sẽ báo lỗi:
# Traceback (most recent call last):
#   File "/content/PrePATH/create_patches_fp.py", line 2, in <module>
#     from wsi_core.WholeSlideImage import WholeSlideImage
#   File "/content/PrePATH/wsi_core/WholeSlideImage.py", line 14, in <module>
#     from Aslide import Slide
# ModuleNotFoundError: No module named 'Aslide'

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/PrePATH

save_dir = '/content/drive/MyDrive/CS231/tcga_dataset/lusc_patches'
wsi_dir = '/content/drive/MyDrive/CS231/tcga_dataset/lusc'
wsi_format = 'svs'
log_name = "LUSC_log"

!python create_patches_fp.py \
        --source $wsi_dir \
        --save_dir $save_dir --preset tcga.csv \
        --patch_level 1 \
        --wsi_format $wsi_format \
        --seg \
        --patch \
        --stitch

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/PrePATH

save_dir = '/content/drive/MyDrive/CS231/tcga_dataset/luad_patches'
wsi_dir = '/content/drive/MyDrive/CS231/tcga_dataset/luad'
wsi_format = 'svs'
log_name = 'LUAD_log'

!python create_patches_fp.py \
        --source $wsi_dir \
        --save_dir $save_dir --preset tcga.csv \
        --patch_level 1 \
        --wsi_format $wsi_format \
        --seg \
        --patch \
        --stitch